apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application-monitoring: 'true'
  name: application-monitoring
spec:
  endpoints:
    - path: /auth/realms/master/metrics
      port: sso
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      application: sso
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: application-monitoring
    role: alert-rules
  name: application-monitoring
spec:
  groups:
    - name: general.rules
      rules:
        - alert: KeycloakDeadMansSwitch
          annotations:
            description: >-
              This is a KeycloakDeadMansSwitch meant to ensure that the entire Alerting
              pipeline is functional.
            summary: Alerting KeycloakDeadMansSwitch
          expr: vector(1)
          labels:
            severity: none